name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello guys"
      - run: ls -la
      - run: echo "escribo un archivo de texto" > demo.txt
      - run: cat demo.txt
      - run: rm -rf demo.txt
      - run: ls -la
      